import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.Namespace;
import org.jdom2.input.SAXBuilder;
import org.jdom2.output.Format;
import org.jdom2.output.XMLOutputter;

import java.io.StringReader;
import java.util.List;

public class PayrollExtractor {

    public static void main(String[] args) throws Exception {
        String xmlInput = "<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2020 (http://www.altova.com)-->
<Transmission xmlns="http://www.irs.gov/efile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.irs.gov/efile file:///S:/PRM/Shared/FSET/SCHEMA/FSETV5.6/FSET/Transmission.xsd">
	<!-- THIS SECTION WILL BE GENERATED USING THE TOOL-->
	<TransmissionHeader recordCount="1">
	  <Jurisdiction>NYS</Jurisdiction>
	  <TransmissionId>15463202430600012064</TransmissionId>
		<!-- 20 Characters (5 digit ETIN + ccyyddd + 8-character alphanumeric)-->	  
	  <Timestamp>2024-11-29T09:14:18-05:00</Timestamp>
	  <Transmitter>
		<ETIN>15463</ETIN>
		<!-- or EFIN -->
	  </Transmitter>
	  <ProcessType>C</ProcessType>
	  <AckAddress>christy.linder@tax.ny.gov</AckAddress>
	</TransmissionHeader>
	<!-- START HERE-->
	<ReturnState stateSchemaVersion="FSETV5.6">
		<SubmissionId>10261120243066010594</SubmissionId>
		<!--20 digits (6 digit EFIN + ccyyddd + 7-character alphanumeric)-->
		<ReturnHeaderState binaryAttachmentCount="0">
			<Jurisdiction>NYS</Jurisdiction>
			<Timestamp>2024-11-26T09:47:11-05:00</Timestamp>
			<TaxPeriodBeginDate>2024-04-01</TaxPeriodBeginDate>
			<!-- Liability period begin date (YYYY-01-01, YYYY-04-01, YYYY-07-01, YYYY-10-01)-->
			<TaxPeriodEndDate>2024-06-30</TaxPeriodEndDate>
			<!-- Liability period end date (YYYY-03-31, YYYY-06-30, YYYY-09-30, YYYY-12-31)-->						
			<SoftwareId>12345</SoftwareId>
			<SoftwareVersion>SoftwareVersion</SoftwareVersion>
			<InternetProtocol>
				<IPAddress>
					<IPv4AddressTxt>31.154.63.138</IPv4AddressTxt>
					<!--or IPv6AddressTxt -->
				</IPAddress>
				<IPTimestamp>2024-11-26T09:47:11-05:00</IPTimestamp>
			</InternetProtocol>
				
			<Filer>
				<TIN>
					<TypeTIN>FEIN</TypeTIN>
					<!-- DO NOT CHANGE-->
					<TINTypeValue>000000000</TINTypeValue>
					<!-- DO NOT CHANGE-->
				</TIN>				
				<StateEIN>111559254</StateEIN>
				<!-- Withholding Identification Number-->
				<StateEINExtension>6754387</StateEINExtension>
				<!-- UI ER Number-->
				<Name>
					<BusinessNameLine1Txt>3945 CORP</BusinessNameLine1Txt>
					<!--Employer's Legal Name-->					
				</Name>				
				<NameControl>3945</NameControl>
				<USAddress>
					<AddressLine1Txt>4 MAIN ST</AddressLine1Txt>					
					<CityNm>ALBANY</CityNm>
					<StateAbbreviationCd>NY</StateAbbreviationCd>
					<ZIPCd>12204</ZIPCd>
				</USAddress>
					<!-- Employer US address-->
					<!-- or ForeignAddress-->
			</Filer>			
			<Form>NYS-45</Form>
			<!--Must be 'NYS-45'-->
			<FilingAction>
				<Action>Original</Action>
				<!-- Must be Original or Amended-->				
			</FilingAction>
			<!--FinalReturnElect CPW-->			
		</ReturnHeaderState>
		<ReturnDataState>
			<StateGeneralInformation>
				<EmployerHealthInsuranceCode>Y</EmployerHealthInsuranceCode>
				<!--Dependent health insurance benefits-->				
				<!-- Seasonal employer indicator-->				
				<ReturnSigner>
					<Name>Lester Pimples Sr</Name>
					<Title>Owner</Title>
					<Phone>9144791155</Phone>
					<EmailAddress>hourlyrates@yahoo.com</EmailAddress>
					<Signature>0123456789</Signature>
					<DateSigned>2024-09-01</DateSigned>
				</ReturnSigner>
			</StateGeneralInformation>
			<StateCombined>
				<WHPaymentsOrDeposits>46216.24</WHPaymentsOrDeposits>
				<!-- WT Part B Line 15 Form NYS-1 payments made for quarter-->
				<WHTotalPayments>48763.13</WHTotalPayments>
				<!-- WT Part B Line 17 Total payments-->
				<WHAmountRemitted>11047.23</WHAmountRemitted>
				<!-- WT Part B Total WT amount remitted-->
				<WHOtherAdjustment>0.00</WHOtherAdjustment>
				<!-- (Amended) WT Part B Line 16 WT payments made with previously filed Forms NYS-45-->
				<WHTotalTax>59810.36</WHTotalTax>
				<!-- WT Part B Line 13 Total tax withheld-->
				<TotalOverPaymentPrevious>2546.89</TotalOverPaymentPrevious>
				<!-- WT Part B Line 14 WT credit from previous quarter's return-->
				<TotalAmendedOverPayment>0.00</TotalAmendedOverPayment>
				<!-- (Amended)WT Part B Line 18 WT overpayment-->
				<WHBalanceDue>11047.23</WHBalanceDue>						
				<LocalTaxWithheld>
					<LocalJurisdiction>NYS</LocalJurisdiction>
					<!--WR Part C Line 23 Column h Total NYS tax withheld-->
					<LocalTaxAmount>51900.30</LocalTaxAmount>
					<!--WR Part C Line 23 Column h Total NYS tax withheld-->
				</LocalTaxWithheld>
				<LocalTaxWithheld>
					<LocalJurisdiction>NYC</LocalJurisdiction>
					<!--WR Part C Line 23 Column i Total NYC tax withheld-->
					<LocalTaxAmount>5970.04</LocalTaxAmount>
					<!--WR Part C Line 23 Column i Total NYC tax withheld-->
				</LocalTaxWithheld>
				<LocalTaxWithheld>
					<LocalJurisdiction>YNK</LocalJurisdiction>
					<!--WR Part C Line 23 Column j Total Yonkers tax withheld-->
					<LocalTaxAmount>1940.02</LocalTaxAmount>
					<!--WR Part C Line 23 Column j Total Yonkers tax withheld-->
				</LocalTaxWithheld>
				<Credit>
					<CreditAmount>0.00</CreditAmount>
				</Credit>				
				<Month3Liability>0.00</Month3Liability>
				<!-- (Amended) UI Part A Line 1a Total remuneration paid this quarter (corrected)-->
				<TotalQuarterLiability>0.00</TotalQuarterLiability>
				<!-- (Amended) UI Part A Line 1b Total remuneration paid this quarter (difference)-->
				<UITotalWages>356823.00</UITotalWages>
				<!--UI Part A Line 1 Total remuneration paid this quarter-->
				<ExcessWages>292823.00</ExcessWages>
				<!--UI Part A Line 2 Remuneration paid in excess-->
				<UITaxableWages>64000.00</UITaxableWages>
				<!--UI Part A Line 3 Wages subject to contribution-->
				<ContributionRate>.03400</ContributionRate>
				<!--UI Part A Line 4 UI Rate-->
				<ContributionDue>2176.00</ContributionDue>
				<!--UI Part A Line 4 UI contributions due-->
				<SurchargeDue>48.00</SurchargeDue>
				<!--UI Part A Line 5 Re-employment service fund-->
				<DIContributionDue>0.00</DIContributionDue>
				<!-- (Amended) UI Part A Line 2a Remuneration paid in excess (corrected)-->
				<TrainingFundContribution>0.00</TrainingFundContribution>
				<!-- (Amended) UI Part A Line 2b Remuneration paid in excess (difference)-->
				<TotalContingencyAssessmentDue>0.00</TotalContingencyAssessmentDue>
				<!-- (Amended) UI Part A Line 5a Re-employment service fund (corrected)-->
				<UIAmountPaid>2331.58</UIAmountPaid>
				<!--UI Part A Total UI amount remitted-->
				<UIAmountDuePreviousPeriod>0.00</UIAmountDuePreviousPeriod>
				<!-- (Amended) UI Part A Line 3a Wages subject to contribution (corrected)-->
				<UICreditPreviousPeriod>0.00</UICreditPreviousPeriod>
				<!--UI Part A Line 9 UI previously overpaid-->
				<UIInterest>107.58</UIInterest>
				<!--UI Part A Line 7 UI previously underpaid with interest-->
				<UIInterestPaid>0.00</UIInterestPaid>
				<!-- (Amended) UI Part A Line 3b Wages subject to contribution (difference)-->
				<UIPenalty>0.00</UIPenalty>
				<!-- (Amended) UI PArt A Line 4a UI contributions due (corrected)-->
				<UITotalDue>2331.58</UITotalDue>
				<!--UI Part A Line 10 Total UI amounts due-->
				<PayRoll>
					<Employee>
						<Employee>
							<FirstName>Shane</FirstName>
							<!-- WR Part C column c-->
							<MiddleInitial>S</MiddleInitial>
							<!-- WR Part C column d-->
							<LastName>Saw</LastName>
							<!-- WR Part C column b-->
							<SSN>113367115</SSN>
							<!-- WR Part C column a-->
						</Employee>
						<TotalWages>65489.15</TotalWages>
						<!-- WR Part C column f (Total UI remuneration paid this quarter)-->
						<TaxableWages>65000.20</TaxableWages>
						<!-- WR Part C column g (Gross fedral wages or distribution)-->
						<WagePlan>0</WagePlan>
						<!-- WR Part C column e (Wage type)-->
						<!-- 0= Regular Wages 1= Other wages -->
						<OutOfStateWages>
							<TotalWages>9750.03</TotalWages>
							<!-- WR Part C column h (Total NYS tax withheld)-->
							<TaxableWages>0</TaxableWages>
							<!-- Must be 0-->
							<TaxState>NYS</TaxState>
							<!-- Must be 'NYS'-->
						</OutOfStateWages>
						<OutOfStateWages>
							<TotalWages>1950.01</TotalWages>
							<!-- WR Part C column i (Total NYC tax withheld)-->
							<TaxableWages>0</TaxableWages>
							<!-- Must be 0-->
							<TaxState>NYC</TaxState>
							<!-- Must be 'NYC'-->
						</OutOfStateWages>
						<OutOfStateWages>
							<TotalWages>650.02</TotalWages>
							<!-- WR Part C column j (Total Yonkers tax withheld)-->
							<TaxableWages>0</TaxableWages>
							<!-- Must be 0-->
							<TaxState>YNK</TaxState>
							<!-- Must be 'YNK'-->
						</OutOfStateWages>
					</Employee>
					<Employee>
						<Employee>
							<FirstName>John</FirstName>
							<!-- WR Part C column c-->
							<MiddleInitial>A</MiddleInitial>
							<!-- WR Part C column d-->
							<LastName>Anderson</LastName>
							<!-- WR Part C column b-->
							<SSN>113367116</SSN>
							<!-- WR Part C column a-->
						</Employee>
						<TotalWages>72113.32</TotalWages>
						<!-- WR Part C column f (Total UI remuneration paid this quarter)-->
						<TaxableWages>72000.40</TaxableWages>
						<!-- WR Part C column g (Gross fedral wages or distribution)-->
						<WagePlan>0</WagePlan>
						<!-- WR Part C column e (Wage type)-->
						<!-- 0= Regular Wages 1= Other wages -->
						<OutOfStateWages>
							<TotalWages>10800.06</TotalWages>
							<!-- WR Part C column h (Total NYS tax withheld)-->
							<TaxableWages>0</TaxableWages>
							<!-- Must be 0-->
							<TaxState>NYS</TaxState>
							<!-- Must be 'NYS'-->
						</OutOfStateWages>
						<OutOfStateWages>
							<TotalWages>2160.01</TotalWages>
							<!-- WR Part C column i (Total NYC tax withheld)-->
							<TaxableWages>0</TaxableWages>
							<!-- Must be 0-->
							<TaxState>NYC</TaxState>
							<!-- Must be 'NYC'-->
						</OutOfStateWages>
						<OutOfStateWages>
							<TotalWages>0.00</TotalWages>
							<!-- WR Part C column j (Total Yonkers tax withheld)-->
							<TaxableWages>0</TaxableWages>
							<!-- Must be 0-->
							<TaxState>YNK</TaxState>
							<!-- Must be 'YNK'-->
						</OutOfStateWages>
					</Employee>
					<Employee>
						<Employee>
							<FirstName>Sally</FirstName>
							<!-- WR Part C column c-->
							<MiddleInitial>Y</MiddleInitial>
							<!-- WR Part C column d-->
							<LastName>York</LastName>
							<!-- WR Part C column b-->
							<SSN>113367117</SSN>
							<!-- WR Part C column a-->
						</Employee>
						<TotalWages>69176.45</TotalWages>
						<!-- WR Part C column f (Total UI remuneration paid this quarter)-->
						<TaxableWages>67000.60</TaxableWages>
						<!-- WR Part C column g (Gross fedral wages or distribution)-->
						<WagePlan>0</WagePlan>
						<!-- WR Part C column e (Wage type)-->
						<!-- 0= Regular Wages 1= Other wages -->
						<OutOfStateWages>
							<TotalWages>10050.09</TotalWages>
							<!-- WR Part C column h (Total NYS tax withheld)-->
							<TaxableWages>0</TaxableWages>
							<!-- Must be 0-->
							<TaxState>NYS</TaxState>
							<!-- Must be 'NYS'-->
						</OutOfStateWages>
						<OutOfStateWages>
							<TotalWages>0.00</TotalWages>
							<!-- WR Part C column i (Total NYC tax withheld)-->
							<TaxableWages>0</TaxableWages>
							<!-- Must be 0-->
							<TaxState>NYC</TaxState>
							<!-- Must be 'NYC'-->
						</OutOfStateWages>
						<OutOfStateWages>
							<TotalWages>670.00</TotalWages>
							<!-- WR Part C column j (Total Yonkers tax withheld)-->
							<TaxableWages>0</TaxableWages>
							<!-- Must be 0-->
							<TaxState>YNK</TaxState>
							<!-- Must be 'YNK'-->
						</OutOfStateWages>
					</Employee>
					<Employee>
						<Employee>
							<FirstName>Shawn</FirstName>
							<!-- WR Part C column c-->
							<MiddleInitial>B</MiddleInitial>
							<!-- WR Part C column d-->
							<LastName>Burton</LastName>
							<!-- WR Part C column b-->
							<SSN>113367118</SSN>
							<!-- WR Part C column a-->
						</Employee>
						<TotalWages>67215.25</TotalWages>
						<!-- WR Part C column f (Total UI remuneration paid this quarter)-->
						<TaxableWages>62000.80</TaxableWages>
						<!-- WR Part C column g (Gross fedral wages or distribution)-->
						<WagePlan>0</WagePlan>
						<!-- WR Part C column e (Wage type)-->
						<!-- 0= Regular Wages 1= Other wages -->
						<OutOfStateWages>
							<TotalWages>9300.12</TotalWages>
							<!-- WR Part C column h (Total NYS tax withheld)-->
							<TaxableWages>0</TaxableWages>
							<!-- Must be 0-->
							<TaxState>NYS</TaxState>
							<!-- Must be 'NYS'-->
						</OutOfStateWages>
						<OutOfStateWages>
							<TotalWages>1860.02</TotalWages>
							<!-- WR Part C column i (Total NYC tax withheld)-->
							<TaxableWages>0</TaxableWages>
							<!-- Must be 0-->
							<TaxState>NYC</TaxState>
							<!-- Must be 'NYC'-->
						</OutOfStateWages>
						<OutOfStateWages>
							<TotalWages>620.00</TotalWages>
							<!-- WR Part C column j (Total Yonkers tax withheld)-->
							<TaxableWages>0</TaxableWages>
							<!-- Must be 0-->
							<TaxState>YNK</TaxState>
							<!-- Must be 'YNK'-->
						</OutOfStateWages>
					</Employee>
					<Employee>
						<Employee>
							<FirstName>Kristie</FirstName>
							<!-- WR Part C column c-->
							<MiddleInitial>W</MiddleInitial>
							<!-- WR Part C column d-->
							<LastName>Williams</LastName>
							<!-- WR Part C column b-->
							<SSN>113367119</SSN>
							<!-- WR Part C column a-->
						</Employee>
						<TotalWages>82828.80</TotalWages>
						<!-- WR Part C column f (Total UI remuneration paid this quarter)-->
						<TaxableWages>80000.00</TaxableWages>
						<!-- WR Part C column g (Gross fedral wages or distribution)-->
						<WagePlan>1</WagePlan>
						<!-- WR Part C column e (Wage type)-->
						<!-- 0= Regular Wages 1= Other wages -->
						<OutOfStateWages>
							<TotalWages>12000.00</TotalWages>
							<!-- WR Part C column h (Total NYS tax withheld)-->
							<TaxableWages>0</TaxableWages>
							<!-- Must be 0-->
							<TaxState>NYS</TaxState>
							<!-- Must be 'NYS'-->
						</OutOfStateWages>
						<OutOfStateWages>
							<TotalWages>0.00</TotalWages>
							<!-- WR Part C column i (Total NYC tax withheld)-->
							<TaxableWages>0</TaxableWages>
							<!-- Must be 0-->
							<TaxState>NYC</TaxState>
							<!-- Must be 'NYC'-->
						</OutOfStateWages>
						<OutOfStateWages>
							<TotalWages>0.00</TotalWages>
							<!-- WR Part C column j (Total Yonkers tax withheld)-->
							<TaxableWages>0</TaxableWages>
							<!-- Must be 0-->
							<TaxState>YNK</TaxState>
							<!-- Must be 'YNK'-->
						</OutOfStateWages>
					</Employee>
				</PayRoll>
				<Month1Employees>5</Month1Employees>
				<!-- UI Part A Number of Employees first month-->
				<Month2Employees>5</Month2Employees>
				<!-- UI Part A Number of Employees second month-->
				<Month3Employees>5</Month3Employees>
				<!-- UI Part A Number of Employees third month-->
			</StateCombined>
		</ReturnDataState>
		<FinancialTransaction>
			<StatePayment>
				<!--For WT Payment-->
				<Checking>X</Checking>
				<!-- or Savings-->
				<RoutingTransitNumber>221373383</RoutingTransitNumber>
				<BankAccountNumber>12345</BankAccountNumber>
				<PaymentAmount>11047.23</PaymentAmount>
				<!-- Must equal WHAmountRemitted-->
				<AccountHolderName>wtAmountCheck</AccountHolderName>
				<AccountHolderType>1</AccountHolderType>
				<!-- 1= Business 2= Personal-->
				<RequestedPaymentDate>2024-11-26</RequestedPaymentDate>
				<AddendaRecord>
					<TaxTypeCode>
						<FTACode>000</FTACode>
						<!-- Must be '000'-->
						<StateTaxTypeCode>02</StateTaxTypeCode>
						<!-- Must be '02' for WT payment-->
					</TaxTypeCode>
				</AddendaRecord>
				<NotIATTransaction>X</NotIATTransaction>
				<!-- or IsIATTransaction-->
			</StatePayment>
			<StatePayment>
				<!--For UI Payment-->
				<Savings>X</Savings>
				<!-- or Checking-->
				<RoutingTransitNumber>221373383</RoutingTransitNumber>
				<BankAccountNumber>12345</BankAccountNumber>
				<PaymentAmount>2331.58</PaymentAmount>
				<!-- Must equal UIAmountPaid-->
				<AccountHolderName>uiAmountCheck</AccountHolderName>
				<AccountHolderType>1</AccountHolderType>
				<!-- 1= Business 2= Personal-->
				<RequestedPaymentDate>2024-11-26</RequestedPaymentDate>
				<AddendaRecord>
					<TaxTypeCode>
						<FTACode>000</FTACode>
						<!-- Must be '000'-->
						<StateTaxTypeCode>01</StateTaxTypeCode>
						<!-- Must be '01' for UI payment-->
					</TaxTypeCode>
				</AddendaRecord>
				<NotIATTransaction>X</NotIATTransaction>
				<!-- or IsIATTransaction-->
			</StatePayment>
		</FinancialTransaction>
	</ReturnState>
</Transmission>
"; // Replace with actual XML content

       
        SAXBuilder builder = new SAXBuilder();
        Document document = builder.build(new StringReader(xmlInput));

        Namespace ns = Namespace.getNamespace("http://www.irs.gov/efile");

        // Navigate to PayRoll
        Element root = document.getRootElement(); // <Transmission>
        Element returnState = root.getChild("ReturnState", ns);
        Element returnDataState = returnState.getChild("ReturnDataState", ns);
        Element stateCombined = returnDataState.getChild("StateCombined", ns);
        Element payroll = stateCombined.getChild("PayRoll", ns);

        // Count number of Employee elements
        int employeeCount = 0;
        if (payroll != null) {
            List<Element> employees = payroll.getChildren("Employee", ns);
            employeeCount = employees.size();
        }

        // Remove PayRoll from XML
        if (payroll != null) {
            stateCombined.removeContent(payroll);
        }

        // Output the cleaned XML
        XMLOutputter outputter = new XMLOutputter(Format.getPrettyFormat());
        String cleanedXml = outputter.outputString(document);

        System.out.println("Employee Count: " + employeeCount);
        System.out.println("Cleaned XML:\n" + cleanedXml);
    }
}
